Feature/lit 462 remove verification steps from relayer
LIT-Protocol/js-sdk pull request #124
Opened 2023-05-30 13:23 UTC by joshLong145

# What
- Supports removing the authentication implementations present within the current relayer for allowing the Relayer server to be a pure pass through for minting and fetching PKP's.
- Adds `getRelayerRequest` method to `BaseProvider` for constructing new `RelayerRequest` for minting or querying PKP's.

2023-05-30 14:26 UTC, hwrdtm requested changes
- can you run prettier on your branch? Seems there's inconsistent spacing here and there.
- also some comments around unification across the auth method types, in this PR and also in the relayer PR

2023-05-30 14:26 UTC, hwrdtm commented on packages/types/src/lib/interfaces.ts
> +	userId: string,
why is the tab spacing inconsistent?

2023-05-30 14:26 UTC, hwrdtm commented on packages/lit-auth-client/src/lib/providers/OtpProvider.ts
> + * @returns {string}- userId contained within the token message
this seems inconsistent with the logic - we're returning a map

2023-05-30 14:26 UTC, hwrdtm commented on packages/lit-auth-client/src/lib/providers/OtpProvider.ts
> +  public override async getRelayerRequest(): Promise<RelayerRequest> {
can unify this across the providers?

2023-05-30 16:42 UTC, joshLong145 commented on packages/lit-auth-client/src/lib/providers/OtpProvider.ts
> +  #parseJWT(jwt: string): Record<string, unknown> {
This was just migrated from the relayer, can bring in a package. but this would bloat the package size im pretty sure.

2023-06-15 12:03 UTC, Ansonhkg commented
Has all the required changes been made yet?

2023-06-27 19:34 UTC, sarahzdev commented on packages/lit-auth-client/src/lib/providers/BaseProvider.ts
> +   * Constrcuts a request for interfacing with relayer minting servers, based on the provider-specific implementation.
```suggestion
   * Constructs a request for interfacing with relayer minting servers, based on the provider-specific implementation.
```

2023-06-27 19:34 UTC, sarahzdev commented on packages/lit-auth-client/src/lib/providers/BaseProvider.ts
> +   * @returns {Promise<RegistrationMethod>} Registraction Method object that contains metdata used for registering authentication methods.
```suggestion
   * @returns {Promise<RegistrationMethod>} Registration method object that contains metadata used for registering authentication methods.
```

2023-07-15 00:18 UTC, hwrdtm commented
As discussed, we should update this PR to work with the new endpoints introduced in https://github.com/LIT-Protocol/relay-server/pull/28.

2023-07-18 21:28 UTC, joshLong145 commented
closing for now with modified changes to the relayer. Branch will be kept open

2024-02-02 12:51 UTC, closed without merging