add bls encryption and decryption e2e testS
LIT-Protocol/js-sdk pull request #303
Opened 2024-01-12 23:12 UTC by FedericoAmura

# Description

This PR adds a few e2e NodeJS tests for BLS encryption / decryption

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-12 23:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LIT-Protocol/js-sdk?pullRequest=303) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LIT-Protocol/js-sdk?pullRequest=303) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LIT-Protocol/js-sdk?pullRequest=303) it.</sub>

2024-01-12 23:51 UTC, Ansonhkg submitted a review, later dismissed
lgtm! let's merge this!

2024-01-13 00:03 UTC, joshLong145 requested changes
Looks good, thanks for getting this done so quickly.

One thing is that we should add these new tests to `ci.yml` in the `e2e-connection` runner as a new test group to run. Since we are not covering BLS encryption features in our ci test runs this will be a great addition.

2024-01-13 01:32 UTC, FedericoAmura commented
> Looks good, thanks for getting this done so quickly.
> 
> One thing is that we should add these new tests to `ci.yml` in the `e2e-connection` runner as a new test group to run. Since we are not covering BLS encryption features in our ci test runs this will be a great addition.

Missed that. I thought it ran every test group.

Added, now those are running here too

2024-01-13 13:31 UTC, joshLong145 approved these changes

2024-01-13 13:31 UTC, merged