fix: wrong encoding - should be `base58` instead of `base64`
LIT-Protocol/js-sdk pull request #652
Opened 2024-09-25 15:35 UTC by Ansonhkg

# Description

Fix wrong encoding - it should be `base58` instead of `base64`.

As per @spacesailor24 comment for the following Lit Action:

```
const transaction = Transaction.from(
  Buffer.from(unsignedTransaction.serializedTransaction, 'base64')
);

transaction.sign(solanaKeyPair);
const signature = transaction.signature.toString('base64');

if (broadcast) {
  const solanaConnection = new Connection(
    clusterApiUrl(unsignedTransaction.chain),
    'confirmed'
  );
  const transactionSignature = await solanaConnection.sendRawTransaction(
    transaction.serialize()
  );

  Lit.Actions.setResponse({ response: transactionSignature });
} else {
  Lit.Actions.setResponse({ response: signature });
}
```

When broadcast is true, transactionSignature will be base58 encoded, but when false, signature is base64 encoded

2024-09-25 16:33 UTC, MaximusHaximus approved these changes
:+1: good catch!

2024-09-25 16:41 UTC, FedericoAmura commented
This made me realize a few things considering these LA maintenance

1. Probably we need a way to update those LAs on publish? And a test to validate that the LA in `wrapped-keys-lit-actions` is the same as the CID in `wrapped-keys``
2. Updating any LA changes its CID, so this change also needs to update that [here](https://github.com/LIT-Protocol/js-sdk/blob/master/packages/wrapped-keys/src/lib/lit-actions-client/constants.ts#L6) with the updated one
3. We also have [this repo](https://github.com/LIT-Protocol/wrapped-key-fallback-service) serving the LAs **unbundled** code in an express app. If that is used I think we could update it to serve the bundled version from the SDK, or unbundled from this repo to avoid duplicating work there

2024-09-25 16:47 UTC, Ansonhkg commented
> This made me realize a few things considering these LA maintenance
> 
> 1. Probably we need a way to update those LAs on publish? And a test to validate that the LA in `wrapped-keys-lit-actions` is the same as the CID in `wrapped-keys``
> 2. Updating any LA changes its CID, so this change also needs to update that [here](https://github.com/LIT-Protocol/js-sdk/blob/master/packages/wrapped-keys/src/lib/lit-actions-client/constants.ts#L6) with the updated one
> 3. We also have [this repo](https://github.com/LIT-Protocol/wrapped-key-fallback-service) serving the LAs **unbundled** code in an express app. If that is used I think we could update it to serve the bundled version from the SDK, or unbundled from this repo to avoid duplicating work there
> 
> cc. @MaximusHaximus

re:  ... express app. If that is used ...

No, it’s not used - It was the initial idea for bundling the LA code, but we disregarded it because we don’t want to maintain another microservice.

2024-09-25 16:48 UTC, MaximusHaximus commented
> This made me realize a few things considering these LA maintenance
> 
> 1. Probably we need a way to update those LAs on publish? And a test to validate that the LA in `wrapped-keys-lit-actions` is the same as the CID in `wrapped-keys``
> 2. Updating any LA changes its CID, so this change also needs to update that [here](https://github.com/LIT-Protocol/js-sdk/blob/master/packages/wrapped-keys/src/lib/lit-actions-client/constants.ts#L6) with the updated one
> 3. We also have [this repo](https://github.com/LIT-Protocol/wrapped-key-fallback-service) serving the LAs **unbundled** code in an express app. If that is used I think we could update it to serve the bundled version from the SDK, or unbundled from this repo to avoid duplicating work there
> 
> cc. @MaximusHaximus

Yes - we currently handle publishing these as an entirely manual process, but now that this is its own package it would be awesome to get the publishing to IPFS codified into the project scripts for this package.

What do you think about adding publishing script to this package, and during build+publish to NPM, we actually compute the CID of these actions after bundling them, and _generate_ the LitActionCidRepository in _this_ package, then import it into `wrapped-keys` 🤔....? With tree shaking, people using the CID repository wouldn't end up with the action source code in their app.

We could even replicate the `setLitActionCode()` method -- we could import the litActionCidRepository from this package as a default, but allow `setLitActionCids()` to be called by consumers of the primary package to use custom actions without being forced to bundle their custom actions source into their app. 🤔

2024-10-01 00:18 UTC, spacesailor24 requested changes
I just found out that ethers includes [base58 en/decoding](https://docs.ethers.org/v5/api/utils/encoding/#Bse58), so we don't have to import `bs58`

2024-10-01 12:56 UTC, Ansonhkg commented
> I just found out that ethers includes [base58 en/decoding](https://docs.ethers.org/v5/api/utils/encoding/#Bse58), so we don't have to import `bs58`

Good catch! Thanks!!

2024-10-01 13:35 UTC, merged